/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/klIx7TtlipH
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Caudex } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

caudex({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import Link from "next/link"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"

export function First() {
  return (
    (<div className="flex flex-col min-h-[100dvh]">
      <header className="px-4 lg:px-6 h-14 flex items-center justify-between">
        <Link className="flex items-center" href="#">
          <FolderSyncIcon className="h-6 w-6" />
          <span className="sr-only">SynapseRise</span>
        </Link>
        <div className="flex items-center gap-4">
          <div className="text-sm text-gray-500" />
        </div>
      </header>
      <main className="flex-1">
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-[#5f27cd] to-[#e84393]">
          <div
            className="container px-4 md:px-6 flex flex-col items-center text-center space-y-6 md:space-y-10">
            <h1
              className="text-4xl font-bold tracking-tighter text-white sm:text-5xl md:text-6xl lg:text-7xl animate-bounce">
              SynapseRise Hackathon
            </h1>
            <p className="max-w-[700px] text-lg text-gray-200 md:text-xl lg:text-2xl">
              Connecting talent, igniting ideas, and solving campus problems through technology.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-white px-8 text-sm font-medium text-[#5f27cd] shadow transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                href="#">
                Register Now
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-white px-8 text-sm font-medium text-white shadow-sm transition-colors hover:bg-white hover:text-[#5f27cd] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                href="#">
                Learn More
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container px-4 md:px-6 grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="flex flex-col items-center text-center space-y-4">
              <ClubIcon className="h-12 w-12 text-[#5f27cd]" />
              <h3 className="text-2xl font-bold">Conference</h3>
              <p className="text-gray-500">Attend inspiring talks and workshops led by industry experts.</p>
            </div>
            <div className="flex flex-col items-center text-center space-y-4">
              <HighlighterIcon className="h-12 w-12 text-[#5f27cd]" />
              <h3 className="text-2xl font-bold">Showcase</h3>
              <p className="text-gray-500">Demonstrate your innovative solutions to a panel of judges.</p>
            </div>
            <div className="flex flex-col items-center text-center space-y-4">
              <ClubIcon className="h-12 w-12 text-[#5f27cd]" />
              <h3 className="text-2xl font-bold">Staff Congress</h3>
              <p className="text-gray-500">Connect with campus leaders and discuss real-world challenges.</p>
            </div>
            <div className="flex flex-col items-center text-center space-y-4">
              <BetweenVerticalStartIcon className="h-12 w-12 text-[#5f27cd]" />
              <h3 className="text-2xl font-bold">Startup Battles</h3>
              <p className="text-gray-500">Compete for prizes and gain valuable feedback from experts.</p>
            </div>
          </div>
        </section>
        <section
          className="w-full py-12 md:py-24 lg:py-32 bg-gradient-to-r from-[#5f27cd] to-[#e84393]">
          <div
            className="container px-4 md:px-6 flex flex-col items-center text-center space-y-6 md:space-y-10">
            <h2
              className="text-4xl font-bold tracking-tighter text-white sm:text-5xl md:text-6xl lg:text-7xl">
              Join the Movement
            </h2>
            <p className="max-w-[700px] text-lg text-gray-200 md:text-xl lg:text-2xl">
              Be part of the SynapseRise Hackathon and help shape the future of campus technology.
            </p>
            <div className="flex flex-col sm:flex-row gap-4">
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md bg-white px-8 text-sm font-medium text-[#5f27cd] shadow transition-colors hover:bg-gray-100 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50"
                href="#">
                Register Now
              </Link>
              <Link
                className="inline-flex h-10 items-center justify-center rounded-md border border-gray-200 border-white px-8 text-sm font-medium text-white shadow-sm transition-colors hover:bg-white hover:text-[#5f27cd] focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-gray-950 disabled:pointer-events-none disabled:opacity-50 dark:border-gray-800"
                href="#">
                Learn More
              </Link>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container px-4 md:px-6 flex flex-col items-center text-center space-y-6 md:space-y-10">
            <h2
              className="text-4xl font-bold tracking-tighter text-[#5f27cd] sm:text-5xl md:text-6xl lg:text-7xl">
              Our Sponsors
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-3 gap-8">
              <div className="flex items-center justify-center">
                <img
                  alt="Sponsor 1"
                  className="max-w-full h-auto"
                  height={50}
                  src="/softgapslogo.jpeg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                    borderRadius: "0.3rem"
                  }}
                  width={150} />
              </div>
              <div className="flex items-center justify-center">
                <img
                  alt="Sponsor 2"
                  className="max-w-full h-auto"
                  height={50}
                  src="/futminnalogo.jpeg"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                    borderRadius: "0.3rem"
                  }}
                  width={150} />
              </div>
              <div className="flex items-center justify-center">
                <img
                  alt="Sponsor 3"
                  className="max-w-full h-auto"
                  height={50}
                  src="/ttflogo.png"
                  style={{
                    aspectRatio: "100/100",
                    objectFit: "cover",
                    borderRadius: "0.3rem"
                  }}
                  width={150} />
              </div>
            </div>
          </div>
        </section>
        <section className="w-full py-12 md:py-24 lg:py-32">
          <div
            className="container px-4 md:px-6 flex flex-col items-center text-center space-y-6 md:space-y-10">
            <h2
              className="text-4xl font-bold tracking-tighter text-[#5f27cd] sm:text-5xl md:text-6xl lg:text-7xl">
              Our Team
            </h2>
            <div
              className="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 gap-8">
              <div className="flex flex-col items-center space-y-4">
                <Avatar className="w-20 h-20 border-4 border-[#5f27cd]">
                  <AvatarImage alt="Team Member 1" src="/team-member-1.jpg" />
                  <AvatarFallback>TM1</AvatarFallback>
                </Avatar>
                <div className="text-lg font-bold">John Doe</div>
                <div className="text-gray-500">Co-Founder</div>
              </div>
              <div className="flex flex-col items-center space-y-4">
                <Avatar className="w-20 h-20 border-4 border-[#5f27cd]">
                  <AvatarImage alt="Team Member 2" src="/team-member-2.jpg" />
                  <AvatarFallback>TM2</AvatarFallback>
                </Avatar>
                <div className="text-lg font-bold">Jane Smith</div>
                <div className="text-gray-500">Lead Designer</div>
              </div>
              <div className="flex flex-col items-center space-y-4">
                <Avatar className="w-20 h-20 border-4 border-[#5f27cd]">
                  <AvatarImage alt="Team Member 3" src="/team-member-3.jpg" />
                  <AvatarFallback>TM3</AvatarFallback>
                </Avatar>
                <div className="text-lg font-bold">Michael Johnson</div>
                <div className="text-gray-500">Lead Developer</div>
              </div>
              <div className="flex flex-col items-center space-y-4">
                <Avatar className="w-20 h-20 border-4 border-[#5f27cd]">
                  <AvatarImage alt="Team Member 4" src="/team-member-4.jpg" />
                  <AvatarFallback>TM4</AvatarFallback>
                </Avatar>
                <div className="text-lg font-bold">Emily Davis</div>
                <div className="text-gray-500">Project Manager</div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer
        className="flex flex-col gap-4 sm:flex-row py-6 w-full shrink-0 items-center px-4 md:px-6 border-t">
        <div className="flex flex-col sm:flex-row items-center gap-4">
          <p className="text-xs text-gray-500">© 2024 SynapseRise. All rights reserved.</p>
          <nav className="flex gap-4 sm:gap-6">
            <Link
              className="text-xs hover:underline underline-offset-4 text-gray-500"
              href="#">
              Terms of Service
            </Link>
            <Link
              className="text-xs hover:underline underline-offset-4 text-gray-500"
              href="#">
              Privacy
            </Link>
          </nav>
        </div>
        <div className="flex items-center gap-4 sm:ml-auto">
          <Button
            className="w-8 h-8 hover:bg-transparent text-gray-500 hover:text-gray-900"
            size="icon"
            variant="ghost">
            <TwitterIcon className="h-5 w-5" />
            <span className="sr-only">Twitter</span>
          </Button>
          <Button
            className="w-8 h-8 hover:bg-transparent text-gray-500 hover:text-gray-900"
            size="icon"
            variant="ghost">
            <InstagramIcon className="h-5 w-5" />
            <span className="sr-only">Instagram</span>
          </Button>
          <Button
            className="w-8 h-8 hover:bg-transparent text-gray-500 hover:text-gray-900"
            size="icon"
            variant="ghost">
            <LinkedinIcon className="h-5 w-5" />
            <span className="sr-only">LinkedIn</span>
          </Button>
        </div>
      </footer>
    </div>)
  );
}

function BetweenVerticalStartIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="7" height="13" x="3" y="8" rx="1" />
      <path d="m15 2-3 3-3-3" />
      <rect width="7" height="13" x="14" y="8" rx="1" />
    </svg>)
  );
}


function ClubIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M17.28 9.05a5.5 5.5 0 1 0-10.56 0A5.5 5.5 0 1 0 12 17.66a5.5 5.5 0 1 0 5.28-8.6Z" />
      <path d="M12 17.66L12 22" />
    </svg>)
  );
}


function FolderSyncIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M9 20H4a2 2 0 0 1-2-2V5a2 2 0 0 1 2-2h3.9a2 2 0 0 1 1.69.9l.81 1.2a2 2 0 0 0 1.67.9H20a2 2 0 0 1 2 2v.5" />
      <path d="M12 10v4h4" />
      <path d="m12 14 1.535-1.605a5 5 0 0 1 8 1.5" />
      <path d="M22 22v-4h-4" />
      <path d="m22 18-1.535 1.605a5 5 0 0 1-8-1.5" />
    </svg>)
  );
}


function HighlighterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m9 11-6 6v3h9l3-3" />
      <path d="m22 12-4.6 4.6a2 2 0 0 1-2.8 0l-5.2-5.2a2 2 0 0 1 0-2.8L14 4" />
    </svg>)
  );
}


function InstagramIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <rect width="20" height="20" x="2" y="2" rx="5" ry="5" />
      <path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z" />
      <line x1="17.5" x2="17.51" y1="6.5" y2="6.5" />
    </svg>)
  );
}


function LinkedinIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z" />
      <rect width="4" height="12" x="2" y="9" />
      <circle cx="4" cy="4" r="2" />
    </svg>)
  );
}


function TwitterIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path
        d="M22 4s-.7 2.1-2 3.4c1.6 10-9.4 17.3-18 11.6 2.2.1 4.4-.6 6-2C3 15.5.5 9.6 3 5c2.2 2.6 5.6 4.1 9 4-.9-4.2 4-6.6 7-3.8 1.1 0 3-1.2 3-1.2z" />
    </svg>)
  );
}
