/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/xXq7VZrcNjZ
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { SheetTrigger, SheetContent, Sheet } from "@/components/ui/sheet"
import Link from "next/link"

export function Navbar() {
  return (
    (<header
      className="flex h-20 w-full shrink-0 items-center px-4 bg-gradient-to-r from-[#9b59b6] to-[#e74c3c] text-white">
      <Sheet>
        <SheetTrigger asChild>
          <Button className="lg:hidden" size="icon" variant="outline">
            <MenuIcon className="h-6 w-6 text-white" />
            <span className="sr-only">Toggle navigation menu</span>
          </Button>
        </SheetTrigger>
        <SheetContent side="left">
          <Link className="mr-6 flex items-center" href="#">
            <MountainIcon className="h-6 w-6 text-white" />
            <span className="ml-2 text-lg font-bold">InnoTheHack</span>
          </Link>
          <nav className="mt-6 flex flex-col items-start gap-4">
            <Link
              className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
              href="#">
              Home
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
              href="#">
              About
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
              href="/">
              Sponsors
            </Link>
            <Link
              className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
              href="#">
              Contact
            </Link>
          </nav>
        </SheetContent>
      </Sheet>
      <div className="ml-auto hidden lg:flex items-center gap-6">
        <Link
          className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
          href="#">
          Home
        </Link>
        <Link
          className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
          href="#">
          About
        </Link>
        <Link
          className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
          href="#">
          Sponsors
        </Link>
        <Link
          className="text-sm font-medium hover:underline underline-offset-4 hover:text-[#f1c40f]"
          href="#">
          Contact
        </Link>
        <Link
          className="inline-flex h-9 items-center justify-center rounded-md bg-[#f1c40f] px-4 py-2 text-sm font-medium text-[#9b59b6] shadow transition-colors hover:bg-[#f1c40f]/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-[#e74c3c] disabled:pointer-events-none disabled:opacity-50 dark:bg-[#e74c3c] dark:text-[#9b59b6] dark:hover:bg-[#e74c3c]/90 dark:focus-visible:ring-[#f1c40f]"
          href="#">
          Register
        </Link>
      </div>
    </header>)
  );
}

function MenuIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <line x1="4" x2="20" y1="12" y2="12" />
      <line x1="4" x2="20" y1="6" y2="6" />
      <line x1="4" x2="20" y1="18" y2="18" />
    </svg>)
  );
}


function MountainIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="m8 3 4 8 5-5 5 15H2L8 3z" />
    </svg>)
  );
}
