/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/zXOZKZa1DHK
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Judson } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

judson({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { ResponsiveBar } from "@nivo/bar"
import { ResponsiveLine } from "@nivo/line"
import { ResponsivePie } from "@nivo/pie"
import Link from "next/link"

export function Sponsor() {
  return (
    (<div className="bg-gradient-to-br from-[#e74c3c] to-[#8e44ad] text-white">
      <header className="py-8 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto">
          <h1 className="text-4xl font-bold tracking-tight sm:text-5xl lg:text-6xl">Sponsor innoTheHack</h1>
          <p className="mt-6 text-xl leading-8">Join us in empowering the next generation of cybersecurity experts.</p>
        </div>
      </header>
      <main>
        <section className="py-16 px-4 sm:px-6 lg:px-8">
          <div className="container mx-auto">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
              <div>
                <h2 className="text-3xl font-bold tracking-tight">Why Sponsor Us?</h2>
                <p className="mt-4 text-lg leading-8">
                  The Africa Cyber Fest is a high-profile event that brings together industry leaders, academics, and
                  government organizations to address the growing cybersecurity challenges facing the African continent.
                </p>
                <p className="mt-4 text-lg leading-8">
                  As Africa's digital landscape continues to expand, the region's vulnerability to cyber threats has
                  become increasingly apparent. Cybercriminals target critical infrastructure, financial institutions,
                  and personal data, causing widespread disruption and financial losses.
                </p>
                <p className="mt-4 text-lg leading-8">
                  By sponsoring the innoTheHack Hackathon, you have the opportunity to showcase your commitment to
                  strengthening Africa's cybersecurity ecosystem. Your support will contribute to the success of expert
                  sessions, workshops, networking opportunities, hacking challenges, and ideas proliferation, all of
                  which are designed to foster knowledge sharing and capacity building.
                </p>
              </div>
              <div className="flex items-center justify-center">
                <div className="rounded-lg bg-white/10 p-8 shadow-lg">
                  <h3 className="text-2xl font-bold">What to Expect</h3>
                  <ul className="mt-4 space-y-4 text-lg">
                    <li>
                      <CircleCheckIcon className="mr-2 inline-block h-6 w-6 text-[#e74c3c]" />
                      Expert sessions and workshops
                    </li>
                    <li>
                      <CircleCheckIcon className="mr-2 inline-block h-6 w-6 text-[#e74c3c]" />
                      Networking opportunities
                    </li>
                    <li>
                      <CircleCheckIcon className="mr-2 inline-block h-6 w-6 text-[#e74c3c]" />
                      Hacking challenges
                    </li>
                    <li>
                      <CircleCheckIcon className="mr-2 inline-block h-6 w-6 text-[#e74c3c]" />
                      Ideas proliferation
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white/10">
          <div className="container mx-auto">
            <h2 className="text-3xl font-bold tracking-tight text-center">Previous Event Stats</h2>
            <div className="mt-10 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-3">
              <div className="rounded-lg bg-white/10 p-8 shadow-lg">
                <h3 className="text-2xl font-bold">Attendees</h3>
                <div className="mt-4">
                  <BarChart className="aspect-[4/3]" />
                </div>
              </div>
              <div className="rounded-lg bg-white/10 p-8 shadow-lg">
                <h3 className="text-2xl font-bold">Sponsorship Revenue</h3>
                <div className="mt-4">
                  <LineChart className="aspect-[4/3]" />
                </div>
              </div>
              <div className="rounded-lg bg-white/10 p-8 shadow-lg">
                <h3 className="text-2xl font-bold">Hacking Challenges</h3>
                <div className="mt-4">
                  <PieChart className="aspect-square" />
                </div>
              </div>
            </div>
          </div>
        </section>
        <section className="py-16 px-4 sm:px-6 lg:px-8 bg-white/10">
          <div className="container mx-auto">
            <h2 className="text-3xl font-bold tracking-tight text-center">Our Sponsors</h2>
            <p className="mt-4 text-lg leading-8 text-center">Thank you to our generous sponsors for their support.</p>
            <div className="mt-10 grid grid-cols-2 gap-8 sm:grid-cols-3 lg:grid-cols-5">
              <div className="flex justify-center">
                <img
                  alt="Sponsor Logo 1"
                  className="max-h-12 w-auto"
                  height={50}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/50",
                    objectFit: "cover",
                  }}
                  width={150} />
              </div>
              <div className="flex justify-center">
                <img
                  alt="Sponsor Logo 2"
                  className="max-h-12 w-auto"
                  height={50}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/50",
                    objectFit: "cover",
                  }}
                  width={150} />
              </div>
              <div className="flex justify-center">
                <img
                  alt="Sponsor Logo 3"
                  className="max-h-12 w-auto"
                  height={50}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/50",
                    objectFit: "cover",
                  }}
                  width={150} />
              </div>
              <div className="flex justify-center">
                <img
                  alt="Sponsor Logo 4"
                  className="max-h-12 w-auto"
                  height={50}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/50",
                    objectFit: "cover",
                  }}
                  width={150} />
              </div>
              <div className="flex justify-center">
                <img
                  alt="Sponsor Logo 5"
                  className="max-h-12 w-auto"
                  height={50}
                  src="/placeholder.svg"
                  style={{
                    aspectRatio: "150/50",
                    objectFit: "cover",
                  }}
                  width={150} />
              </div>
            </div>
          </div>
        </section>
        <section className="py-16 px-4 sm:px-6 lg:px-8">
          <div className="container mx-auto">
            <div className="grid grid-cols-1 gap-8 md:grid-cols-2">
              <div>
                <h2 className="text-3xl font-bold tracking-tight">Become a Sponsor</h2>
                <p className="mt-4 text-lg leading-8">
                  By sponsoring the innoTheHack Hackathon, you can demonstrate your commitment to strengthening Africa's
                  cybersecurity ecosystem and support the next generation of cybersecurity experts.
                </p>
                <p className="mt-4 text-lg leading-8">
                  Sponsorship opportunities are available at various levels, allowing you to choose the package that
                  best fits your organization's goals and budget.
                </p>
                <div className="mt-6">
                  <Link
                    className="inline-flex items-center rounded-md bg-[#e74c3c] px-4 py-2 text-lg font-medium text-white shadow-sm hover:bg-[#c0392b] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[#e74c3c] focus-visible:ring-offset-2"
                    href="#">
                    Learn More
                  </Link>
                </div>
              </div>
              <div className="flex items-center justify-center">
                <div className="rounded-lg bg-white/10 p-8 shadow-lg">
                  <h3 className="text-2xl font-bold">Sponsorship Levels</h3>
                  <ul className="mt-4 space-y-4 text-lg">
                    <li>
                      <div className="flex items-center">
                        <div className="h-4 w-4 rounded-full bg-[#e74c3c]" />
                        <span className="ml-2">Platinum</span>
                      </div>
                    </li>
                    <li>
                      <div className="flex items-center">
                        <div className="h-4 w-4 rounded-full bg-[#9b59b6]" />
                        <span className="ml-2">Gold</span>
                      </div>
                    </li>
                    <li>
                      <div className="flex items-center">
                        <div className="h-4 w-4 rounded-full bg-[#7e5e9f]" />
                        <span className="ml-2">Silver</span>
                      </div>
                    </li>
                    <li>
                      <div className="flex items-center">
                        <div className="h-4 w-4 rounded-full bg-[#6c5b7b]" />
                        <span className="ml-2">Bronze</span>
                      </div>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </section>
      </main>
      <footer className="bg-white/10 py-8 px-4 sm:px-6 lg:px-8">
        <div className="container mx-auto">
          <p className="text-center text-lg">© 2024 innoTheHack. All rights reserved.</p>
        </div>
      </footer>
    </div>)
  );
}

function BarChart(props) {
  return (
    (<div {...props}>
      <ResponsiveBar
        data={[
          { name: "Jan", count: 111 },
          { name: "Feb", count: 157 },
          { name: "Mar", count: 129 },
          { name: "Apr", count: 150 },
          { name: "May", count: 119 },
          { name: "Jun", count: 72 },
        ]}
        keys={["count"]}
        indexBy="name"
        margin={{ top: 0, right: 0, bottom: 40, left: 40 }}
        padding={0.3}
        colors={["#2563eb"]}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 4,
          tickPadding: 16,
        }}
        gridYValues={4}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        tooltipLabel={({ id }) => `${id}`}
        enableLabel={false}
        role="application"
        ariaLabel="A bar chart showing data" />
    </div>)
  );
}


function CircleCheckIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>)
  );
}


function LineChart(props) {
  return (
    (<div {...props}>
      <ResponsiveLine
        data={[
          {
            id: "Desktop",
            data: [
              { x: "Jan", y: 43 },
              { x: "Feb", y: 137 },
              { x: "Mar", y: 61 },
              { x: "Apr", y: 145 },
              { x: "May", y: 26 },
              { x: "Jun", y: 154 },
            ],
          },
          {
            id: "Mobile",
            data: [
              { x: "Jan", y: 60 },
              { x: "Feb", y: 48 },
              { x: "Mar", y: 177 },
              { x: "Apr", y: 78 },
              { x: "May", y: 96 },
              { x: "Jun", y: 204 },
            ],
          },
        ]}
        margin={{ top: 10, right: 10, bottom: 40, left: 40 }}
        xScale={{
          type: "point",
        }}
        yScale={{
          type: "linear",
        }}
        axisTop={null}
        axisRight={null}
        axisBottom={{
          tickSize: 0,
          tickPadding: 16,
        }}
        axisLeft={{
          tickSize: 0,
          tickValues: 5,
          tickPadding: 16,
        }}
        colors={["#2563eb", "#e11d48"]}
        pointSize={6}
        useMesh={true}
        gridYValues={6}
        theme={{
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
          grid: {
            line: {
              stroke: "#f3f4f6",
            },
          },
        }}
        role="application" />
    </div>)
  );
}


function PieChart(props) {
  return (
    (<div {...props}>
      <ResponsivePie
        data={[
          { id: "Jan", value: 111 },
          { id: "Feb", value: 157 },
          { id: "Mar", value: 129 },
          { id: "Apr", value: 150 },
          { id: "May", value: 119 },
          { id: "Jun", value: 72 },
        ]}
        sortByValue
        margin={{ top: 10, right: 10, bottom: 10, left: 10 }}
        cornerRadius={0}
        padAngle={0}
        borderWidth={1}
        borderColor={"#ffffff"}
        enableArcLinkLabels={false}
        arcLabel={(d) => `${d.id}`}
        arcLabelsTextColor={"#ffffff"}
        arcLabelsRadiusOffset={0.65}
        colors={["#2563eb"]}
        theme={{
          labels: {
            text: {
              fontSize: "18px",
            },
          },
          tooltip: {
            chip: {
              borderRadius: "9999px",
            },
            container: {
              fontSize: "12px",
              textTransform: "capitalize",
              borderRadius: "6px",
            },
          },
        }}
        role="application" />
    </div>)
  );
}
