/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/LUhThTWDe5W
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Timeline() {
  return (
    (<div className="w-full max-w-5xl mx-auto p-6 sm:p-10">
      <div className="grid gap-8">
        <div className="text-center space-y-2">
          <h1 className="text-3xl font-bold tracking-tight sm:text-4xl">Hackathon Timeline</h1>
          <p className="text-gray-500 dark:text-gray-400">
            Follow the key events and milestones of our upcoming hackathon.
          </p>
        </div>
        <div
          className="relative before:absolute before:inset-x-0 before:h-px before:bg-gray-200 dark:before:bg-gray-700">
          <ol className="relative z-10 grid grid-cols-5 gap-8">
            <li className="flex flex-col items-center">
              <div
                className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex items-center justify-center">
                <CalendarIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              </div>
              <div className="mt-2 text-sm font-medium">Registration</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">March 1 - March 15</div>
            </li>
            <li className="flex flex-col items-center">
              <div
                className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex items-center justify-center">
                <BookOpenIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              </div>
              <div className="mt-2 text-sm font-medium">Workshops</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">March 16 - March 17</div>
            </li>
            <li className="flex flex-col items-center">
              <div
                className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex items-center justify-center">
                <CodeIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              </div>
              <div className="mt-2 text-sm font-medium">Hacking</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">March 18 - March 20</div>
            </li>
            <li className="flex flex-col items-center">
              <div
                className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex items-center justify-center">
                <PresentationIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              </div>
              <div className="mt-2 text-sm font-medium">Demos</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">March 21</div>
            </li>
            <li className="flex flex-col items-center">
              <div
                className="bg-gray-100 dark:bg-gray-800 rounded-full p-3 flex items-center justify-center">
                <TrophyIcon className="w-6 h-6 text-gray-500 dark:text-gray-400" />
              </div>
              <div className="mt-2 text-sm font-medium">Awards</div>
              <div className="text-xs text-gray-500 dark:text-gray-400">March 21</div>
            </li>
          </ol>
        </div>
      </div>
    </div>)
  );
}

function BookOpenIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 3h6a4 4 0 0 1 4 4v14a3 3 0 0 0-3-3H2z" />
      <path d="M22 3h-6a4 4 0 0 0-4 4v14a3 3 0 0 1 3-3h7z" />
    </svg>)
  );
}


function CalendarIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M8 2v4" />
      <path d="M16 2v4" />
      <rect width="18" height="18" x="3" y="4" rx="2" />
      <path d="M3 10h18" />
    </svg>)
  );
}


function CodeIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <polyline points="16 18 22 12 16 6" />
      <polyline points="8 6 2 12 8 18" />
    </svg>)
  );
}


function PresentationIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M2 3h20" />
      <path d="M21 3v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V3" />
      <path d="m7 21 5-5 5 5" />
    </svg>)
  );
}


function TrophyIcon(props) {
  return (
    (<svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round">
      <path d="M6 9H4.5a2.5 2.5 0 0 1 0-5H6" />
      <path d="M18 9h1.5a2.5 2.5 0 0 0 0-5H18" />
      <path d="M4 22h16" />
      <path d="M10 14.66V17c0 .55-.47.98-.97 1.21C7.85 18.75 7 20.24 7 22" />
      <path d="M14 14.66V17c0 .55.47.98.97 1.21C16.15 18.75 17 20.24 17 22" />
      <path d="M18 2H6v7a6 6 0 0 0 12 0V2Z" />
    </svg>)
  );
}
